//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSTCPEndpoint
{
    [Serializable]
    public class CompressedImageMsg : Message
    {
        public const string k_RosMessageName = "ROS_TCP_Endpoint_msgs/CompressedImage";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public string format;
        public byte[] data;

        public CompressedImageMsg()
        {
            this.header = new Std.HeaderMsg();
            this.format = "";
            this.data = new byte[0];
        }

        public CompressedImageMsg(Std.HeaderMsg header, string format, byte[] data)
        {
            this.header = header;
            this.format = format;
            this.data = data;
        }

        public static CompressedImageMsg Deserialize(MessageDeserializer deserializer) => new CompressedImageMsg(deserializer);

        private CompressedImageMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.format);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.format);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "CompressedImageMsg: " +
            "\nheader: " + header.ToString() +
            "\nformat: " + format.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
