//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSTCPEndpoint
{
    [Serializable]
    public class ConsoleInfoMsg : Message
    {
        public const string k_RosMessageName = "ROS_TCP_Endpoint_msgs/ConsoleInfo";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public byte code;
        public string content;

        public ConsoleInfoMsg()
        {
            this.header = new Std.HeaderMsg();
            this.code = 0;
            this.content = "";
        }

        public ConsoleInfoMsg(Std.HeaderMsg header, byte code, string content)
        {
            this.header = header;
            this.code = code;
            this.content = content;
        }

        public static ConsoleInfoMsg Deserialize(MessageDeserializer deserializer) => new ConsoleInfoMsg(deserializer);

        private ConsoleInfoMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.code);
            deserializer.Read(out this.content);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.code);
            serializer.Write(this.content);
        }

        public override string ToString()
        {
            return "ConsoleInfoMsg: " +
            "\nheader: " + header.ToString() +
            "\ncode: " + code.ToString() +
            "\ncontent: " + content.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
