//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSTCPEndpoint
{
    [Serializable]
    public class HMDInputMsg : Message
    {
        public const string k_RosMessageName = "ROS_TCP_Endpoint_msgs/HMDInput";
        public override string RosMessageName => k_RosMessageName;

        public float HMD_pos_x;
        public float HMD_pos_y;
        public float HMD_pos_z;
        public float HMD_rot_x;
        public float HMD_rot_y;
        public float HMD_rot_z;
        public float HMD_rot_w;

        public HMDInputMsg()
        {
            this.HMD_pos_x = 0.0f;
            this.HMD_pos_y = 0.0f;
            this.HMD_pos_z = 0.0f;
            this.HMD_rot_x = 0.0f;
            this.HMD_rot_y = 0.0f;
            this.HMD_rot_z = 0.0f;
            this.HMD_rot_w = 0.0f;
        }

        public HMDInputMsg(float HMD_pos_x, float HMD_pos_y, float HMD_pos_z, float HMD_rot_x, float HMD_rot_y, float HMD_rot_z, float HMD_rot_w)
        {
            this.HMD_pos_x = HMD_pos_x;
            this.HMD_pos_y = HMD_pos_y;
            this.HMD_pos_z = HMD_pos_z;
            this.HMD_rot_x = HMD_rot_x;
            this.HMD_rot_y = HMD_rot_y;
            this.HMD_rot_z = HMD_rot_z;
            this.HMD_rot_w = HMD_rot_w;
        }

        public static HMDInputMsg Deserialize(MessageDeserializer deserializer) => new HMDInputMsg(deserializer);

        private HMDInputMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.HMD_pos_x);
            deserializer.Read(out this.HMD_pos_y);
            deserializer.Read(out this.HMD_pos_z);
            deserializer.Read(out this.HMD_rot_x);
            deserializer.Read(out this.HMD_rot_y);
            deserializer.Read(out this.HMD_rot_z);
            deserializer.Read(out this.HMD_rot_w);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.HMD_pos_x);
            serializer.Write(this.HMD_pos_y);
            serializer.Write(this.HMD_pos_z);
            serializer.Write(this.HMD_rot_x);
            serializer.Write(this.HMD_rot_y);
            serializer.Write(this.HMD_rot_z);
            serializer.Write(this.HMD_rot_w);
        }

        public override string ToString()
        {
            return "HMDInputMsg: " +
            "\nHMD_pos_x: " + HMD_pos_x.ToString() +
            "\nHMD_pos_y: " + HMD_pos_y.ToString() +
            "\nHMD_pos_z: " + HMD_pos_z.ToString() +
            "\nHMD_rot_x: " + HMD_rot_x.ToString() +
            "\nHMD_rot_y: " + HMD_rot_y.ToString() +
            "\nHMD_rot_z: " + HMD_rot_z.ToString() +
            "\nHMD_rot_w: " + HMD_rot_w.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
